print(‘To receive a yo mama roast, press the keys 1, 2, 3, 4, or, 5.’)
if (keyboard_input.(‘1’))
  print(‘’’Yo mama is so fat that…
  When she went to the fat contest they said…
  “NO PROFFESSIONALS ALLOWED”!’’’)
if (
